# Horoscope.delete_all
# Horoscope.create([
# 	{
# 		name: 'aries',
# 		img: 'http://i.imgur.com/oBB6kHP.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'taurus',
# 		img: 'http://i.imgur.com/eJ0cANL.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'gemini',
# 		img: 'http://i.imgur.com/mc8XRsb.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'cancer',
# 		img: 'http://i.imgur.com/PsWFtDX.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'leo',
# 		img: 'http://i.imgur.com/qZbWPLH.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'virgo',
# 		img: 'http://i.imgur.com/TFVeKK8.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'libra',
# 		img: 'http://i.imgur.com/KJ83Zsk.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'scorpio',
# 		img: 'http://i.imgur.com/SKj3d4O.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'sagittarius',
# 		img: 'http://i.imgur.com/YcNUrLF.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'capricorn',
# 		img: 'http://i.imgur.com/4S3EWwz.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'aquarius',
# 		img: 'http://i.imgur.com/nBwcvPe.png',
# 		likes: 0,
# 		dislikes: 0
# 	}, {
# 		name: 'pisces',
# 		img: 'http://i.imgur.com/QIzB7p9.png',
# 		likes: 0,
# 		dislikes: 0
# 	}
# ])